# === CONFIGURACIÓN DEL SERVIDOR ===
spring.application.name=game
server.port=8080

# === CONFIGURACIÓN DE LA BASE DE DATOS ===
# Si existe DB_URL la usa (Render), si no, usa localhost (Eclipse)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/BDD_TiendaNexus}

# Si existe DB_USER la usa (Render), si no, usa postgres (Eclipse)
spring.datasource.username=${DB_USER:postgres}

# La contraseña siempre debe ser variable obligatoria por seguridad
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# === CONFIGURACIÓN DE JPA / HIBERNATE ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# === VARIABLES DE SEGURIDAD EXTRAS ===
google.maps.api.key=${GOOGLE_MAPS_API_KEY}
admin.panel.password=${ADMIN_PASSWORD}