# === CONFIGURACIÓN DEL SERVIDOR ===
spring.application.name=game
server.port=8080

# === CONFIGURACIÓN DE LA BASE DE DATOS ===
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/BDD_TiendaNexus}
spring.datasource.username=${DB_USER:postgres}

# Aquí está el truco: le decimos que por defecto use "postgres" para que Eclipse no llore,
# pero Render lo reemplazará con la variable DB_PASSWORD.
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# === CONFIGURACIÓN DE JPA / HIBERNATE ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# === VARIABLES DE SEGURIDAD EXTRAS ===
# También le ponemos un valor por defecto temporal para evitar errores de Maven
google.maps.api.key=${GOOGLE_MAPS_API_KEY:clave_local_temporal}
admin.panel.password=${ADMIN_PASSWORD:1234}